### PR TITLE
Read HLT paths names from ConfDB v2

### PR DESCRIPTION
**Pull request by fwyzard**
Here is the update to the query that maps the HLT paths to their names, provided by @sandrov .
However, I have only tested it with sqlplus, so outside of the transfer script.

.Andrea

### CODE REVIEW

**Comment by janveverka** [comment]
Thanks Andrea! I haven't noticed this for a while.  I see that there is a plan to update to ConfDB v2 today.  Does this mean that we should deploy this in the same time?

**Comment by fwyzard** [comment]
We have been using v2 for a while (but the data are also available from v1, so far), so you can switch at any time.

**Comment by janveverka** [comment]
Merged to the devel branch at bdd1832c843ec8da41482951295609a26b8f9bd5 and tested. It's ready to be deployed from the devel branch as commit ac135d8f499e1d49532ac57a760cec061204a870.

**Comment by janveverka** [comment]
Deployed yesterday at 14:14 and it seems to be working fine:
http://cmsonline.cern.ch/cms-elog/851086

**Pull request closed without merging**
